### ISSUE TITLE
Calling `Parser.ParseWithContext` from another project throw `TargetParameterCountException`

### ISSUE THREAD

**Issue by bdke** [b3b00/csly#527]
## Info
- OS: Windows
- Package Version: 3.5.1
- Net Version: 9.0.100

## Reproduce Steps
Calling a method that call `Parse<IN, OUT>.ParseWithContext(IList<Token<TokenType>>)` from another project.
> Calling that method in the same project work normally.

## Error Log
```
   at System.Reflection.MethodBaseInvoker.ThrowTargetParameterCountException()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(SyntaxNode`2 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`2 n, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(SyntaxNode`2 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`2 n, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(SyntaxNode`2 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`2 n, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ManySyntaxNode`2 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`2 n, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(SyntaxNode`2 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`2 n, Object context)
   at sly.parser.generator.visitor.SyntaxTreeVisitor`2.VisitSyntaxTree(ISyntaxNode`2 root, Object context)
   at sly.parser.Parser`2.ParseWithContext(IList`1 tokens, Object parsingContext, String startingNonTerminal)
```

**Comment by b3b00** [comment]
@bdke, First could you provide a reproducing test case. 
Secondly I think that `ParseWithContext` needs 2 parameters : 
- a list of token as you provide
- an object instance that will be the actual context. this might be null as default
- and and optional third that is the starting non terminal

So my guess is that there can be an issue when the context object is null , but in this case why wouldn't you use the basic `Parse(IList<Token>)` method as a null context is no context at all.

But then I don't see any relation with the "calling from another project" part of your issue.

So please add a reproducing test case.

Waiting for it I will try and see what happen when calling `ParseWithContext` without a context. 

Thanks

**Comment by b3b00** [comment]
@bdke , I reproduce the exception when calling `ParseWithContext`without the context param. I will look at it. Still could you explain the "calling from another project" part ? How is your solution architected ? which project is ok , and which is not .....
i think this part is not the real problem

**Comment by b3b00** [comment]
@bdke , i've fixed the bug on branch https://github.com/b3b00/csly/tree/bugfix/issue%23527.
I 'm waiting for more context to be sure that the fix is complete. Then I will merge on dev branch and release a new nuget version

**Comment by b3b00** [comment]
@bdke , I've published nes nuget version [3.5.2](https://www.nuget.org/packages/sly/3.5.2) 
As you do not answer to provide more context I close this issue.

**Comment by bdke** [comment]
sorry for the late reply, seem like i am still having the same exception
i will provide a minimum reproducible unit test in pull request

**Comment by bdke** [comment]
instance is null as default so it did not throw any error in IDE so i thought it was an issue
it was my fault. Thanks for your reply
